:retab

diff --git a/doom-launcher b/doom-launcher
--- a/doom-launcher
+++ b/doom-launcher
@@ -26,403 +26,403 @@ noprofile=no
 arg_cli=no
 
 function error() {
-	echo "[ERROR] $*"
-	exit 1
+    echo "[ERROR] $*"
+    exit 1
 }
 
 function prepare() {
-	local dep_program
-	local directory
-	if [ ! "$HOME" ]; then
-		error 'variable missing: HOME'
-	fi
+    local dep_program
+    local directory
+    if [ ! "$HOME" ]; then
+        error 'variable missing: HOME'
+    fi
 
-	if [ ! "$XDG_CONFIG_HOME" ]; then
-		XDG_CONFIG_HOME="$HOME/.config"
-	fi
+    if [ ! "$XDG_CONFIG_HOME" ]; then
+        XDG_CONFIG_HOME="$HOME/.config"
+    fi
 
-	if [ ! "$XDG_CACHE_HOME" ]; then
-		XDG_CACHE_HOME="$HOME/.cache"
-	fi
+    if [ ! "$XDG_CACHE_HOME" ]; then
+        XDG_CACHE_HOME="$HOME/.cache"
+    fi
 
-	config_dir="$XDG_CONFIG_HOME/$program"
-	config_dir_mods="$config_dir/mods"
-	cache_dir="$XDG_CACHE_HOME/$program"
+    config_dir="$XDG_CONFIG_HOME/$program"
+    config_dir_mods="$config_dir/mods"
+    cache_dir="$XDG_CACHE_HOME/$program"
 
-	for directory in "$config_dir" "$cache_dir" "$config_dir_mods"; do
-		if [ ! -d "$directory" ]; then
-			if ! mkdir -p "$directory"; then
-				error "failed to create directory: '$directory'"
-			fi
-		fi
-	done
+    for directory in "$config_dir" "$cache_dir" "$config_dir_mods"; do
+        if [ ! -d "$directory" ]; then
+            if ! mkdir -p "$directory"; then
+                error "failed to create directory: '$directory'"
+            fi
+        fi
+    done
 
-	for dep_program in "${dep_commands[@]}"; do
-		if ! command -v "$dep_program" > /dev/null 2>&1; then
-			error "missing program: '$dep_program'"
-		fi
-	done
+    for dep_program in "${dep_commands[@]}"; do
+        if ! command -v "$dep_program" > /dev/null 2>&1; then
+            error "missing program: '$dep_program'"
+        fi
+    done
 }
 
 function isNew() {
-	if [ -f "$config_dir/${program}.conf" ]; then
-		return 1
-	else
-		return 0
-	fi
+    if [ -f "$config_dir/${program}.conf" ]; then
+        return 1
+    else
+        return 0
+    fi
 }
 
 function msgbox() {
-	if [ ! "$size" ]; then
-		size="0 0"
-	fi
-	dialog --msgbox "$@" $size
+    if [ ! "$size" ]; then
+        size="0 0"
+    fi
+    dialog --msgbox "$@" $size
 }
 
 function launch_doom() {
-	if [ "$arg_cli" = "no" ]; then
-		clear
-	fi
-	if [ "$noprofile" = "no" ]; then
-		load_profile
-	fi
-	if [ ! "$mod_iwad" ]; then
-		mod_iwad="$base_wad"
-	fi
-	unset base_args
-	if [ ! -f "$cache_dir/launch.sh" ]; then
-		chmod=yes
-	fi
-	for mod_file in "${mod_files[@]}"; do
-		base_args+=("-file \"$mod_file\"")
-	done
+    if [ "$arg_cli" = "no" ]; then
+        clear
+    fi
+    if [ "$noprofile" = "no" ]; then
+        load_profile
+    fi
+    if [ ! "$mod_iwad" ]; then
+        mod_iwad="$base_wad"
+    fi
+    unset base_args
+    if [ ! -f "$cache_dir/launch.sh" ]; then
+        chmod=yes
+    fi
+    for mod_file in "${mod_files[@]}"; do
+        base_args+=("-file \"$mod_file\"")
+    done
     if [ "$mod_name" ]
     then
         base_args+=("-savedir \"$save_dir/$mod_name\"")
     fi
-	echo "gzdoom -iwad \"$mod_iwad\" ${base_args[@]}" > "$cache_dir/launch.sh"
-	if [ "$chmod" = "yes" ]; then
-		chmod +x "$cache_dir/launch.sh"
-	fi
-	echo "Launching gzdoom, arguments: '-iwad \"$mod_iwad\" ${base_args[@]} $mod_args'"
-	"$cache_dir/launch.sh" > "$cache_dir/gzdoom_output.log" 2>&1
-	unload_profile
-	if [ "$arg_cli" = "no" ]; then
-		menu_main
-	fi
+    echo "gzdoom -iwad \"$mod_iwad\" ${base_args[@]}" > "$cache_dir/launch.sh"
+    if [ "$chmod" = "yes" ]; then
+        chmod +x "$cache_dir/launch.sh"
+    fi
+    echo "Launching gzdoom, arguments: '-iwad \"$mod_iwad\" ${base_args[@]} $mod_args'"
+    "$cache_dir/launch.sh" > "$cache_dir/gzdoom_output.log" 2>&1
+    unload_profile
+    if [ "$arg_cli" = "no" ]; then
+        menu_main
+    fi
 }
 
 function menu_main() {
-	# Make sure profile is not loaded
-	unload_profile
-	mod_arg_word="Select"
-	if [ -f "$cache_dir/profile" ]; then
-		source "$cache_dir/profile"
-		if [ -f "$mod_profile" ]; then
-			mod_arg_word="Change"
-		fi
-	fi
-	if [ ! "$base_wad" ]; then
-		arg_word="Select"
-	else
-		arg_word="Change"
-	fi
-	input="$(dialog --stdout --nocancel \
-		--title "doom-launcher" \
-		--menu "Main menu" \
-		15 48 5\
-		1 "Launch doom" \
-		2 "$arg_word IWAD" \
-		3 "$mod_arg_word mod profile" \
-		4 "Add mod profile" \
-		5 "Quit")"
-	if [ "$?" != "0" ]; then
-		error "failed to create main menu"
-	fi
-	case "$input" in 
-		1) launch_doom;;
-		2) menu_base_select;;
-		3) menu_mod_select;;
-		4) menu_mod_add;;
-		5) clear; exit;;
-	esac
+    # Make sure profile is not loaded
+    unload_profile
+    mod_arg_word="Select"
+    if [ -f "$cache_dir/profile" ]; then
+        source "$cache_dir/profile"
+        if [ -f "$mod_profile" ]; then
+            mod_arg_word="Change"
+        fi
+    fi
+    if [ ! "$base_wad" ]; then
+        arg_word="Select"
+    else
+        arg_word="Change"
+    fi
+    input="$(dialog --stdout --nocancel \
+        --title "doom-launcher" \
+        --menu "Main menu" \
+        15 48 5\
+        1 "Launch doom" \
+        2 "$arg_word IWAD" \
+        3 "$mod_arg_word mod profile" \
+        4 "Add mod profile" \
+        5 "Quit")"
+    if [ "$?" != "0" ]; then
+        error "failed to create main menu"
+    fi
+    case "$input" in 
+        1) launch_doom;;
+        2) menu_base_select;;
+        3) menu_mod_select;;
+        4) menu_mod_add;;
+        5) clear; exit;;
+    esac
 }
 
 function menu_mod_select() {
-	mod_amount=0
-	first=yes
-	while IFS= read -r file
-	do
-		source "$file"
-		if [ "x$mod_name" != "x" ] && \
-			[ "x${mod_files[0]}" != "x" ] && \
-			[ "x${mod_iwad}" != "x" ]
-		then
-			((mod_amount++))
-			if [ "$first" = "yes" ]; then
-				mod_selection=("$mod_amount ${mod_name// /_}")
-				mod_wads=("${mod_iwad}")
-				mod_selection_files=("$file")
-				first=no
-			else
-				mod_selection+=("$mod_amount ${mod_name// /_}")
-				mod_wads+=("${mod_iwad}")
-				mod_selection_files+=("$file")
-			fi
-		fi
-		unset mod_files mod_name mod_iwad mod_args
-	done < <(find "$config_dir_mods" -type f)
+    mod_amount=0
+    first=yes
+    while IFS= read -r file
+    do
+        source "$file"
+        if [ "x$mod_name" != "x" ] && \
+            [ "x${mod_files[0]}" != "x" ] && \
+            [ "x${mod_iwad}" != "x" ]
+        then
+            ((mod_amount++))
+            if [ "$first" = "yes" ]; then
+                mod_selection=("$mod_amount ${mod_name// /_}")
+                mod_wads=("${mod_iwad}")
+                mod_selection_files=("$file")
+                first=no
+            else
+                mod_selection+=("$mod_amount ${mod_name// /_}")
+                mod_wads+=("${mod_iwad}")
+                mod_selection_files+=("$file")
+            fi
+        fi
+        unset mod_files mod_name mod_iwad mod_args
+    done < <(find "$config_dir_mods" -type f)
 
-	iwad_amount=0
-	first=yes
-	for iwad in "${mod_wads[@]}"; do
-		duplicate=no
-		for _iwad in "${mod_uniq_iwads[@]}"; do
-			[ "$_iwad" = "$iwad" ] && duplicate=yes
-		done
-		if [ "$duplicate" = "no" ]; then
-			((iwad_amount++))
-			if [ "$first" = "yes" ]; then
-				mod_un_iwads=("$iwad_amount ${iwad// /_}")
-				mod_uniq_iwads=("$iwad")
-				first=no
-			else
-				mod_un_iwads+=("$iwad_amount ${iwad// /_}")
-				mod_uniq_iwads+=("$iwad")
-			fi
-		fi
-	done
+    iwad_amount=0
+    first=yes
+    for iwad in "${mod_wads[@]}"; do
+        duplicate=no
+        for _iwad in "${mod_uniq_iwads[@]}"; do
+            [ "$_iwad" = "$iwad" ] && duplicate=yes
+        done
+        if [ "$duplicate" = "no" ]; then
+            ((iwad_amount++))
+            if [ "$first" = "yes" ]; then
+                mod_un_iwads=("$iwad_amount ${iwad// /_}")
+                mod_uniq_iwads=("$iwad")
+                first=no
+            else
+                mod_un_iwads+=("$iwad_amount ${iwad// /_}")
+                mod_uniq_iwads+=("$iwad")
+            fi
+        fi
+    done
 
-	if [ ! "$mod_selection_files" ] && \
-		[ ! "$mod_selection" ] && \
-		[ ! "$mod_wad" ]
-	then
-		size="5 40" msgbox "No mod profile found, please add one"
-	fi
+    if [ ! "$mod_selection_files" ] && \
+        [ ! "$mod_selection" ] && \
+        [ ! "$mod_wad" ]
+    then
+        size="5 40" msgbox "No mod profile found, please add one"
+    fi
 
-	if ! input="$(dialog --stdout \
-			--title "menu_mod_select" \
-			--menu "Select IWAD" \
-			20 60 20 \
-			${mod_un_iwads[@]})"
-	then
-		menu_main
-	fi
+    if ! input="$(dialog --stdout \
+            --title "menu_mod_select" \
+            --menu "Select IWAD" \
+            20 60 20 \
+            ${mod_un_iwads[@]})"
+    then
+        menu_main
+    fi
 
-	i=0
-	amount=0
-	first=yes
-	for iwad in "${mod_wads[@]}"; do
-		if [ "${mod_uniq_iwads[(($input -1))]}" = "$iwad" ]; then
-			((amount++))
-			if [ "$first" = "yes" ]; then
-				mod_selection2=("$amount $(echo "${mod_selection[$i]}"  | cut -d' ' -f2)")
-				mod_selection_files2=("${mod_selection_files[$i]}")
-				first=no
-			else
-				mod_selection2+=("$amount $(echo "${mod_selection[$i]}" | cut -d' ' -f2)")
-				mod_selection_files2+=("${mod_selection_files[$i]}")
-			fi
-		fi
-		((i++))
-	done
-	
-	if ! input="$(dialog --stdout \
-			--title "menu_mod_select" \
-			--menu "Select mod profile" \
-			20 60 $((${#mod_selection2[@]} + 1)) \
-			${mod_selection2[@]})"
-	then
-		menu_main
-	fi
+    i=0
+    amount=0
+    first=yes
+    for iwad in "${mod_wads[@]}"; do
+        if [ "${mod_uniq_iwads[(($input -1))]}" = "$iwad" ]; then
+            ((amount++))
+            if [ "$first" = "yes" ]; then
+                mod_selection2=("$amount $(echo "${mod_selection[$i]}"  | cut -d' ' -f2)")
+                mod_selection_files2=("${mod_selection_files[$i]}")
+                first=no
+            else
+                mod_selection2+=("$amount $(echo "${mod_selection[$i]}" | cut -d' ' -f2)")
+                mod_selection_files2+=("${mod_selection_files[$i]}")
+            fi
+        fi
+        ((i++))
+    done
+    
+    if ! input="$(dialog --stdout \
+            --title "menu_mod_select" \
+            --menu "Select mod profile" \
+            20 60 $((${#mod_selection2[@]} + 1)) \
+            ${mod_selection2[@]})"
+    then
+        menu_main
+    fi
 
-	source "${mod_selection_files[$input]}"
-	echo "mod_profile='${mod_selection_files2[(($input - 1))]}'" > "$cache_dir/profile"
-	menu_main
+    source "${mod_selection_files[$input]}"
+    echo "mod_profile='${mod_selection_files2[(($input - 1))]}'" > "$cache_dir/profile"
+    menu_main
 }
 
 function menu_mod_add() {
-	if [ ! "$mod_name" ]; then
-		arg_word="Add"
-	else
-		arg_word="Change"
-	fi
-	if [ ! "$mod_args" ]; then
-		arg_word2="Add"
-	else
-		arg_word2="Change"
-	fi
-	if ! input="$(dialog --stdout \
-		--title "menu_mod_add" \
-		--menu "Add mod profile" \
-		15 48 5 \
-		1 "$arg_word name" \
-		2 "Add files" \
-		3 "Change IWAD" \
-		4 "$arg_word2 arguments" \
-		5 "Save")" 
-	then
-		menu_main
-	fi
-	case "$input" in 
-		1) menu_mod_add_name; menu_mod_add;;
-		2) menu_mod_add_files;;
-		3) menu_mod_slect_iwad;; 
-		4) menu_mod_add_args; menu_mod_add;;
-		5) menu_mod_add_save;;
-	esac
+    if [ ! "$mod_name" ]; then
+        arg_word="Add"
+    else
+        arg_word="Change"
+    fi
+    if [ ! "$mod_args" ]; then
+        arg_word2="Add"
+    else
+        arg_word2="Change"
+    fi
+    if ! input="$(dialog --stdout \
+        --title "menu_mod_add" \
+        --menu "Add mod profile" \
+        15 48 5 \
+        1 "$arg_word name" \
+        2 "Add files" \
+        3 "Change IWAD" \
+        4 "$arg_word2 arguments" \
+        5 "Save")" 
+    then
+        menu_main
+    fi
+    case "$input" in 
+        1) menu_mod_add_name; menu_mod_add;;
+        2) menu_mod_add_files;;
+        3) menu_mod_slect_iwad;; 
+        4) menu_mod_add_args; menu_mod_add;;
+        5) menu_mod_add_save;;
+    esac
 }
 
 function menu_mod_add_args() {
-	mod_args="$(dialog --stdout \
-			--title "menu_mod_add_args" \
-			--inputbox "$arg_word2 arguments" \
-			10 10 "$mod_args")"
+    mod_args="$(dialog --stdout \
+            --title "menu_mod_add_args" \
+            --inputbox "$arg_word2 arguments" \
+            10 10 "$mod_args")"
 }
 
 function menu_mod_add_name() {
-	mod_name="$(dialog --stdout \
-		--title "menu_mod_add_name" \
-		--inputbox "$arg_word name" \
-		10 10 "$mod_name")"
-	mod_name="${mod_name// /_}"
+    mod_name="$(dialog --stdout \
+        --title "menu_mod_add_name" \
+        --inputbox "$arg_word name" \
+        10 10 "$mod_name")"
+    mod_name="${mod_name// /_}"
 }
 
 function menu_mod_add_files() {
-	input="$(dialog --stdout --nocancel \
-		--title "menu_mod_add_files" \
-		--menu "Add files" \
-		15 48 2 \
-		1 "Add file" \
-		2 "finish")"
-	case "$input" in 
-		1) menu_mod_add_file;;
-		2) menu_mod_add;;
-	esac
+    input="$(dialog --stdout --nocancel \
+        --title "menu_mod_add_files" \
+        --menu "Add files" \
+        15 48 2 \
+        1 "Add file" \
+        2 "finish")"
+    case "$input" in 
+        1) menu_mod_add_file;;
+        2) menu_mod_add;;
+    esac
 }
 
 function menu_mod_add_file() {
-	if ! mod_file="$(dialog --stdout \
-			--fselect "$HOME/" 10 50)"
-	then
-		menu_mod_add_files
-	fi
-	if [ ! -f "$mod_file" ]; then
-		size="5 30" msgbox "Invalid file, try again"
-		menu_mod_add_file
-	else
-		mod_files+=("$mod_file")
-		menu_mod_add_files
-	fi
+    if ! mod_file="$(dialog --stdout \
+            --fselect "$HOME/" 10 50)"
+    then
+        menu_mod_add_files
+    fi
+    if [ ! -f "$mod_file" ]; then
+        size="5 30" msgbox "Invalid file, try again"
+        menu_mod_add_file
+    else
+        mod_files+=("$mod_file")
+        menu_mod_add_files
+    fi
 }
 
 function menu_mod_add_save() {
-	if [ ! "$mod_iwad" ]; then
-		mod_iwad="$base_wad"
-	fi
-	if [ ! "$mod_files" ] || \
-		[ ! "$mod_name" ]
-	then
-		msgbox "Missing information"
-		menu_mod_add
-	else
-		first=yes
-		config_file_name="$config_dir_mods//${mod_name// /_}.conf"
-		if [ -f "$config_file_name" ]; then
-			size="7 50" msgbox "A profile with that name already exists.\\n\\nPlease choose another name"
-			menu_mod_add
-		fi
-		echo "mod_name='$mod_name'" > "$config_file_name"
-		for file in "${mod_files[@]}"; do
-			if [ "$first" = "yes" ]; then
-				first=no
-				echo "mod_files=(\"$file\")"
-			else
-				echo "mod_files+=(\"$file\")"
-			fi 
-		done >> "$config_file_name"
-		echo "mod_iwad=\"$mod_iwad\"" >> "$config_file_name"
-		echo "mod_args=\"$mod_args\"" >> "$config_file_name"
-		sed -i "s|$HOME|\$HOME|g" "$config_file_name"
-	fi
-	unset mod_files mod_name mod_iwad mod_args
-	menu_main
+    if [ ! "$mod_iwad" ]; then
+        mod_iwad="$base_wad"
+    fi
+    if [ ! "$mod_files" ] || \
+        [ ! "$mod_name" ]
+    then
+        msgbox "Missing information"
+        menu_mod_add
+    else
+        first=yes
+        config_file_name="$config_dir_mods//${mod_name// /_}.conf"
+        if [ -f "$config_file_name" ]; then
+            size="7 50" msgbox "A profile with that name already exists.\\n\\nPlease choose another name"
+            menu_mod_add
+        fi
+        echo "mod_name='$mod_name'" > "$config_file_name"
+        for file in "${mod_files[@]}"; do
+            if [ "$first" = "yes" ]; then
+                first=no
+                echo "mod_files=(\"$file\")"
+            else
+                echo "mod_files+=(\"$file\")"
+            fi 
+        done >> "$config_file_name"
+        echo "mod_iwad=\"$mod_iwad\"" >> "$config_file_name"
+        echo "mod_args=\"$mod_args\"" >> "$config_file_name"
+        sed -i "s|$HOME|\$HOME|g" "$config_file_name"
+    fi
+    unset mod_files mod_name mod_iwad mod_args
+    menu_main
 }
 
 function menu_base_select() {
-	if ! base_wad="$(dialog --stdout \
-		--fselect "$HOME/" 10 50)"
-	then
-		menu_main
-	fi
-	echo "base_wad=\"${base_wad/$HOME/\$HOME}\"" > "$config_dir/${program}.conf"
-	menu_main
+    if ! base_wad="$(dialog --stdout \
+        --fselect "$HOME/" 10 50)"
+    then
+        menu_main
+    fi
+    echo "base_wad=\"${base_wad/$HOME/\$HOME}\"" > "$config_dir/${program}.conf"
+    menu_main
 }
 
 function menu_mod_slect_iwad() {
-	if ! mod_iwad="$(dialog --stdout \
-			--fselect "$HOME/" 10 50)"
-	then
-		menu_mod_add
-	fi
-	if [ ! -f "$mod_iwad" ]; then
-		size="5 30" msgbox "Invalid file, try again"
-		menu_mod_add
-	else
-		menu_mod_add
-	fi
+    if ! mod_iwad="$(dialog --stdout \
+            --fselect "$HOME/" 10 50)"
+    then
+        menu_mod_add
+    fi
+    if [ ! -f "$mod_iwad" ]; then
+        size="5 30" msgbox "Invalid file, try again"
+        menu_mod_add
+    else
+        menu_mod_add
+    fi
 }
 
 function load_profile() {
-	if [ "$1" ] && \
-		[ -f "$1" ]
-	then
-		source "$1"
-		return
-	elif [ "$1" ] && [ ! -f "$1" ]; then
-		if [ -f "$config_dir_mods/$1.conf" ]; then
-			source "$config_dir_mods/$1.conf"
-			return
-		elif [ -f "$config_dir_mods/$1" ]; then
-			source "$config_dir_mods/$1"
-			return
-		fi
-	fi
-	if [ -f "$cache_dir/profile" ]; then
-		source "$cache_dir/profile"
-		if [ -f "$mod_profile" ]; then
-			source "$mod_profile"
-		fi
-	fi
+    if [ "$1" ] && \
+        [ -f "$1" ]
+    then
+        source "$1"
+        return
+    elif [ "$1" ] && [ ! -f "$1" ]; then
+        if [ -f "$config_dir_mods/$1.conf" ]; then
+            source "$config_dir_mods/$1.conf"
+            return
+        elif [ -f "$config_dir_mods/$1" ]; then
+            source "$config_dir_mods/$1"
+            return
+        fi
+    fi
+    if [ -f "$cache_dir/profile" ]; then
+        source "$cache_dir/profile"
+        if [ -f "$mod_profile" ]; then
+            source "$mod_profile"
+        fi
+    fi
 }
 
 function unload_profile() {
-	unset mod_files mod_name mod_iwad mod_args
+    unset mod_files mod_name mod_iwad mod_args
 }
 
 function parse_arguments() {
-	for arg in $@
-	do
-		case $arg in
-			--profile=*)
-				noprofile=yes
-				load_profile "${arg/--profile=/}";;
-			--nomods)
-				noprofile=yes;;
-			--launch)
-				arg_cli=yes
-				launch_doom
-				exit;;
-		esac
-	done
+    for arg in $@
+    do
+        case $arg in
+            --profile=*)
+                noprofile=yes
+                load_profile "${arg/--profile=/}";;
+            --nomods)
+                noprofile=yes;;
+            --launch)
+                arg_cli=yes
+                launch_doom
+                exit;;
+        esac
+    done
 
 }
 prepare
 
 if isNew; then
-	size="5 30" msgbox "Welcome to doom-launcher!"
+    size="5 30" msgbox "Welcome to doom-launcher!"
 else
-	source "$config_dir/${program}.conf"
+    source "$config_dir/${program}.conf"
 fi
 
 if [ ! "$save_dir" ]
